-- Table: public.Customers

-- DROP TABLE IF EXISTS public."Customers";

CREATE TABLE IF NOT EXISTS public."Customers"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    membership_id integer NOT NULL DEFAULT 1,
    phone character varying(11) COLLATE pg_catalog."default" NOT NULL,
    dob date NOT NULL,
    CONSTRAINT "PK_Customers" PRIMARY KEY (id),
    CONSTRAINT "FK_Customers_Memberships_membership_id" FOREIGN KEY (membership_id)
        REFERENCES public."Memberships" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Customers"
    OWNER to postgres;
-- Index: IX_Customers_membership_id

-- DROP INDEX IF EXISTS public."IX_Customers_membership_id";

CREATE INDEX IF NOT EXISTS "IX_Customers_membership_id"
    ON public."Customers" USING btree
    (membership_id ASC NULLS LAST)
    TABLESPACE pg_default;