-- Table: public.Districts

-- DROP TABLE IF EXISTS public."Districts";

CREATE TABLE IF NOT EXISTS public."Districts"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    province_id integer NOT NULL,
    CONSTRAINT "PK_Districts" PRIMARY KEY (id),
    CONSTRAINT "FK_Districts_Provinces_province_id" FOREIGN KEY (province_id)
        REFERENCES public."Provinces" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Districts"
    OWNER to postgres;
-- Index: IX_Districts_province_id

-- DROP INDEX IF EXISTS public."IX_Districts_province_id";

CREATE INDEX IF NOT EXISTS "IX_Districts_province_id"
    ON public."Districts" USING btree
    (province_id ASC NULLS LAST)
    TABLESPACE pg_default;