-- Table: public.Memberships

-- DROP TABLE IF EXISTS public."Memberships";

CREATE TABLE IF NOT EXISTS public."Memberships"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default",
    discount_value numeric NOT NULL,
    CONSTRAINT "PK_Memberships" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Memberships"
    OWNER to postgres;