-- Table: public.Order_types

-- DROP TABLE IF EXISTS public."Order_types";

CREATE TABLE IF NOT EXISTS public."Order_types"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default",
    CONSTRAINT "PK_Order_types" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Order_types"
    OWNER to postgres;