-- Table: public.Provinces

-- DROP TABLE IF EXISTS public."Provinces";

CREATE TABLE IF NOT EXISTS public."Provinces"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Provinces" PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Provinces"
    OWNER to postgres;