-- Table: public.Store_products

-- DROP TABLE IF EXISTS public."Store_products";

CREATE TABLE IF NOT EXISTS public."Store_products"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    store_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT "PK_Store_products" PRIMARY KEY (id),
    CONSTRAINT unique_product_store UNIQUE (product_id, store_id),
    CONSTRAINT "FK_Store_products_Products_product_id" FOREIGN KEY (product_id)
        REFERENCES public."Products" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Store_products_Stores_store_id" FOREIGN KEY (store_id)
        REFERENCES public."Stores" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT check_quantity_positive CHECK (quantity >= 0)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Store_products"
    OWNER to postgres;
-- Index: IX_Store_products_product_id

-- DROP INDEX IF EXISTS public."IX_Store_products_product_id";

CREATE INDEX IF NOT EXISTS "IX_Store_products_product_id"
    ON public."Store_products" USING btree
    (product_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Store_products_store_id

-- DROP INDEX IF EXISTS public."IX_Store_products_store_id";

CREATE INDEX IF NOT EXISTS "IX_Store_products_store_id"
    ON public."Store_products" USING btree
    (store_id ASC NULLS LAST)
    TABLESPACE pg_default;