-- Table: public.Stores

-- DROP TABLE IF EXISTS public."Stores";

CREATE TABLE IF NOT EXISTS public."Stores"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1000) COLLATE pg_catalog."default",
    province_id integer NOT NULL,
    district_id integer NOT NULL,
    address character varying(1000) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK_Stores" PRIMARY KEY (id),
    CONSTRAINT "FK_Stores_Districts_district_id" FOREIGN KEY (district_id)
        REFERENCES public."Districts" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Stores_Provinces_province_id" FOREIGN KEY (province_id)
        REFERENCES public."Provinces" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Stores"
    OWNER to postgres;
-- Index: IX_Stores_district_id

-- DROP INDEX IF EXISTS public."IX_Stores_district_id";

CREATE INDEX IF NOT EXISTS "IX_Stores_district_id"
    ON public."Stores" USING btree
    (district_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Stores_province_id

-- DROP INDEX IF EXISTS public."IX_Stores_province_id";

CREATE INDEX IF NOT EXISTS "IX_Stores_province_id"
    ON public."Stores" USING btree
    (province_id ASC NULLS LAST)
    TABLESPACE pg_default;