-- Table: public.Users

-- DROP TABLE IF EXISTS public."Users";

CREATE TABLE IF NOT EXISTS public."Users"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    username character varying(100) COLLATE pg_catalog."default" NOT NULL,
    password character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(11) COLLATE pg_catalog."default" NOT NULL,
    role_id integer NOT NULL,
    store_id integer,
    CONSTRAINT "PK_Users" PRIMARY KEY (id),
    CONSTRAINT "FK_Users_Roles_role_id" FOREIGN KEY (role_id)
        REFERENCES public."Roles" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT "FK_Users_Stores_store_id" FOREIGN KEY (store_id)
        REFERENCES public."Stores" (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Users"
    OWNER to postgres;
-- Index: IX_Users_role_id

-- DROP INDEX IF EXISTS public."IX_Users_role_id";

CREATE INDEX IF NOT EXISTS "IX_Users_role_id"
    ON public."Users" USING btree
    (role_id ASC NULLS LAST)
    TABLESPACE pg_default;
-- Index: IX_Users_store_id

-- DROP INDEX IF EXISTS public."IX_Users_store_id";

CREATE INDEX IF NOT EXISTS "IX_Users_store_id"
    ON public."Users" USING btree
    (store_id ASC NULLS LAST)
    TABLESPACE pg_default;