// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectDatabase.Models;

#nullable disable

namespace ProjectDatabase.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20230622200837_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectDatabase.Models.Customer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("dob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("membership_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.HasKey("id");

                    b.HasIndex("membership_id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ProjectDatabase.Models.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("province_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("province_id");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Membership", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<float>("_value")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("id");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("create_by")
                        .HasColumnType("integer");

                    b.Property<int?>("customer_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("discount_membership")
                        .HasColumnType("numeric");

                    b.Property<decimal>("final_price")
                        .HasColumnType("numeric");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("store_id")
                        .HasColumnType("integer");

                    b.Property<decimal>("total_price")
                        .HasColumnType("numeric");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("create_by");

                    b.HasIndex("customer_id");

                    b.HasIndex("store_id");

                    b.HasIndex("type");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Order_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("id");

                    b.ToTable("Order_types");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Orderline", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("order_id")
                        .HasColumnType("integer");

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("order_id");

                    b.HasIndex("product_id");

                    b.ToTable("Orderlines");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal?>("Price")
                        .IsRequired()
                        .HasColumnType("numeric");

                    b.Property<DateTime>("deleteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("discount")
                        .HasColumnType("real");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("type")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("type");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Product_type", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("id");

                    b.ToTable("Product_Types");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Province", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("id");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Role", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Store", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("district_id")
                        .HasColumnType("integer");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("province_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("district_id");

                    b.HasIndex("province_id");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Store_product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("product_id")
                        .HasColumnType("integer");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<int>("store_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("product_id");

                    b.HasIndex("store_id");

                    b.ToTable("Store_products");
                });

            modelBuilder.Entity("ProjectDatabase.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<int>("role_id")
                        .HasColumnType("integer");

                    b.Property<int?>("store_id")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.HasIndex("store_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Customer", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Membership", "Membership")
                        .WithMany("Customers")
                        .HasForeignKey("membership_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Membership");
                });

            modelBuilder.Entity("ProjectDatabase.Models.District", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Province", "Province")
                        .WithMany("Districts")
                        .HasForeignKey("province_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Order", b =>
                {
                    b.HasOne("ProjectDatabase.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("create_by")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("customer_id");

                    b.HasOne("ProjectDatabase.Models.Store", "Store")
                        .WithMany("Orders")
                        .HasForeignKey("store_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Order_type", "Order_type")
                        .WithMany("Orders")
                        .HasForeignKey("type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order_type");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Orderline", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Order", "Order")
                        .WithMany("Orderlines")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Product", "Product")
                        .WithMany("Orderlines")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Product", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Product_type", "Product_type")
                        .WithMany("Products")
                        .HasForeignKey("type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product_type");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Store", b =>
                {
                    b.HasOne("ProjectDatabase.Models.District", "District")
                        .WithMany("Stores")
                        .HasForeignKey("district_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Province", "Province")
                        .WithMany("Stores")
                        .HasForeignKey("province_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Store_product", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Product", "Product")
                        .WithMany("Store_products")
                        .HasForeignKey("product_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Store", "Store")
                        .WithMany("Store_products")
                        .HasForeignKey("store_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ProjectDatabase.Models.User", b =>
                {
                    b.HasOne("ProjectDatabase.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectDatabase.Models.Store", "Store")
                        .WithMany("Users")
                        .HasForeignKey("store_id");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ProjectDatabase.Models.District", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Membership", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Order", b =>
                {
                    b.Navigation("Orderlines");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Order_type", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Product", b =>
                {
                    b.Navigation("Orderlines");

                    b.Navigation("Store_products");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Product_type", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Province", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectDatabase.Models.Store", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Store_products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("ProjectDatabase.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
